### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-js-objects-T4W3KQ#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://mi-449-ss17-740-js-objects-t4w3kq-GriffinMartin.surge.sh/) and meets the following criteria:

- [x] Your app builds on [these files](https://gist.github.com/chrisvfritz/3bd1b8d8e5b0d1ea2278ffbc561de047) (you can make changes to any of them)
- [x] When the `requestedJokeInput` has a value matching the key of an existing joke, the `jokeBox` HTML is updated [in this format](https://gist.github.com/chrisvfritz/4def3c246dfb931ecb57384a5639af99)
- [x] When the `requestedJokeInput` does _not_ match an existing joke, the `jokeBox` content is updated to `No matching joke found.`
- [x] When the `Remember this joke!` button is clicked, a new joke is saved (or overwritten) in the `jokes` object, using the data in the associated `input`/`textarea` elements
- [x] When the `Forget about it!` button is clicked, the joke with that key (if any) is deleted from the `jokes` object
- [x] Whenever the `jokes` object changes, the new version is saved in `localStorage` and used whenever the user visits the page again
- [x] It's impossible for an error to ever occur in the JavaScript console

localStorage was a pain for me to figure out but I finally got it working! 👍

**Comment by chrisvfritz** [comment]
Looking good. 😄  Just a few areas for improvement:

### `jokeBox` displaying wrong content when no matching joke found

Instead of displaying `No matching joke found.`, it looks like the `jokeBox` is displaying the message that it doesn't know _any_ jokes.

### Clearing inputs

After you click the button to add/remove a joke, let's clear the inputs (set their `value` to an empty string). That way, users won't have to delete those values when they want to type something else.

### Leftover `console.log` statements

Since you're done debugging, let's remove the `console.log` statements to avoid the code getting cluttered.

### Updating the entire page

Right now when you add or delete a joke, it only updates the jokes menu, not the displayed joke. To resolve this, I would simply call `updatePage` instead of `updateJokesMenu` after making changes. Then you'll also be able to remove the `updateJokesObject` call in `updateJokesMenu`.

**Comment by GriffinMartin** [comment]
@chrisvfritz Fixed it up 👍

**Comment by GriffinMartin** [comment]
@chrisvfritz Fixed it up 👍

**Comment by chrisvfritz** [comment]
Looking much better! I only see one more issue, then I'll approve and teach you a new trick. 🙂 

### Error when getting jokes from `localStorage`

I'm not sure why I didn't see this before, but this actually causes an error when `window.localStorage.getItem('joke')` returns `null` (i.e. on the first visit):

``` js
var newJokes = JSON.parse(window.localStorage.getItem('joke'))
```

I think it also probably belongs in the `STARTUP` section rather than `PAGE UPDATERS` (may be part of how I missed it).

**Comment by chrisvfritz** [comment]
Oh, wow, I missed one more thing: [this line](https://github.com/GriffinMartin/MI-449-SS17-740-js-objects-T4W3KQ/blob/master/app.js#L31) isn't actually doing anything.

**Comment by GriffinMartin** [comment]
@chrisvfritz Sweet it should be good now 🎊

**Comment by chrisvfritz** [comment]
Nice emoji! I don't use that one enough! We're _almost_ there. If you run `localStorage.clear()` in the browser's JavaScript console and then refresh, you'll actually still get this error:

```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at updateJokesMenu (app.js:37)
    at updatePage (app.js:60)
    at app.js:75
updateJokesMenu @ app.js:37
updatePage @ app.js:60
(anonymous) @ app.js:75
```

That's because `newJokes` will be `undefined` on a user's first visit, when `joke` in `localStorage` is `null`.

**Comment by GriffinMartin** [comment]
@chrisvfritz 
I fixed up that issue! Thanks for all the feedback 🎆

**Comment by chrisvfritz** [comment]
Looks good. 😄  :shipit: 🎊  🎆 🤘 

### A few additional changes I would make personally

I've just approved the project, so this isn't something you have to change, but I wanted to share a few more refactors I would make:

- Just update `jokes` instead of created a new `newJokes` variable
- Assign `window.localStorage.getItem('joke')` to a `rawJokes` variable, then reuse it instead of fetching it from `localStorage` multiple times
- Save to `jokes` in `localStorage` instead of `joke`

To see what that might look like, I'd set `jokes` to the two starting jokes at the beginning:

``` js
var jokes = {
  'the horse': {
    setup: 'A horse walks into the bar. The bartender asks...',
    punchline: 'Why the long face?'
  },
  'Orion\'s pants': {
    setup: 'How does Orion keep his pants up?',
    punchline: 'With an asteroid belt.'
  }
}
```

Then down in the startup section, I'd do this:

``` js
var rawJokes = window.localStorage.getItem('jokes')
if (rawJokes !== null) {
  jokes = JSON.parse(rawJokes)
}
```

I think this makes the code a little clearer and simpler.

### MEGA BONUS: Solving the problem with Vue!

Since you're diving into Vue, I just put together [this secret gist](https://gist.github.com/chrisvfritz/a82af36f67bb964d52782317d6e9c6ad) to show you an example of how the same app might be built with Vue. 🙂

**Comment by chrisvfritz** [comment]
Oh, and as always, feel free to follow up with more questions if you have any! Keep up the fantastic work!!! 🚀

**Comment by GriffinMartin** [comment]
@chrisvfritz fixed it up!
Wow, thanks for putting together the secret gist with the Vue app!
I'm going to work on breaking it down and figure out what I don't understand!

**Comment by chrisvfritz** [comment]
Sounds great. 😄  If you have any questions, I'll be around.
